security:
    password_hashers:
        App\Entity\Admin:
            algorithm: auto
        App\Entity\Client:
            algorithm: auto
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email
        client_provider:
            entity:
                class: App\Entity\Client
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/(admin|hotel|chambre|service|classement|travaux|dashboard)
            provider: admin_provider
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: app_admin
            logout:
                path: admin_logout
                target: admin_login
        client:
            pattern: ^/(login|logout|client|reservation|register)
            provider: client_provider
            form_login:
                login_path: client_login
                check_path: client_login
                default_target_path: app_client_dashboard
            logout:
                path: client_logout
                target: client_login

    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/hotel, roles: ROLE_ADMIN }
        - { path: ^/chambre, roles: ROLE_ADMIN }
        - { path: ^/service, roles: ROLE_ADMIN }
        - { path: ^/classement, roles: ROLE_ADMIN }
        - { path: ^/travaux, roles: ROLE_ADMIN }
        - { path: ^/dashboard, roles: ROLE_ADMIN }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/client, roles: ROLE_CLIENT }
        - { path: ^/reservation, roles: ROLE_CLIENT }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10